# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcord', '0013_auto_20190905_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcordsubscriber_decl',
            name='downstream_bps',
            field=models.ForeignKey(help_text=b'Downstream Bandwidth Profile for a subscriber', on_delete=django.db.models.deletion.CASCADE, related_name='ds_subscriber', to='rcord.BandwidthProfile_decl'),
        ),
        migrations.AlterField(
            model_name='rcordsubscriber_decl',
            name='upstream_bps',
            field=models.ForeignKey(help_text=b'Upstream Bandwidth Profile for a subscriber', on_delete=django.db.models.deletion.CASCADE, related_name='us_subscriber', to='rcord.BandwidthProfile_decl'),
        ),
    ]
